#add-additional-groups-to-servers
- hosts: localhost
  gather_facts: False
  tasks:
  - name: Validate that serverList is passed from ansible-playbook command
    fail: msg="ansible-playbook <name_of_playbook> -i <myhosts> -e 'serverList=<server1,server2>'"
    when: serverList is not defined

- hosts: "{{ serverList }}"
  gather_facts: True  
  roles:
  - {role: add-additional-groups-to-servers, domain: "{{ ansible_windows_domain }}" }