---
- name: Test Windows Connection
  hosts: windows
#  gather_facts: False
  vars:
    domain: ansible_windows_domain
  tasks:
  - name: Test connection
    debug:
      var: hostvars[inventory_hostname].ansible_windows_domain
