###########################################################################
#   ETIG Automation - Windows Build - Deploy NSVPBIND
#   Confluence:
#   copy NBVSPBIND
#   Author: Barry Field
#   Creation Date: 13/02/19
#   Last Update Date: 13/02/19
###########################################################################


---
- name: Deploy NVSPBIND
  hosts: all
  gather_facts: False
  tasks:

    - name: Copy nvspbind.exe
      win_copy:
        src: "{{ nvspbind_source }}"
        dest: C:\Windows\System32
        state: present