---
# This playbook will provision a VM in vCenter with all validations
- name: Check datastore cluster storage size
  hosts: localhost
  connection: local
  #gather_facts: False
  #vars:
  #  start_execution_date_time: "{{ lookup('pipe','date +Y%-m%-d%-H%-M%-S%') }}"
  roles:
  - build-vm-from-template
  tasks:
  - debug:
      msg: "Playbook execute successfully"
