- name: Gather all registered virtual machines
  hosts: localhost
  connection: local
  vars:
    vcenter_hostname: ukfhpcbvcs02.uk.experian.local
    vcenter_username: 'EXPERIANUK\BladeLogicVMware'
    vcenter_password: 4hQzYa7F5hNFmLvj
    vm_name: "ACITestedf1"
    vm_name_exists: False
  tasks:
    - name: "Testing module "
      #vmware_host_vmnic_facts:
      vmware_portgroup_facts:
      #vmware_vswitch_facts:
      #vmware_vmkernel_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster_name: "FH 40-Core Windows 01"
       # esxi_hostname: "ukfhphysyn07.uk.experian.local"
        validate_certs: False
      delegate_to: localhost
      register: vm_facts
    #- set_fact:
     #   vm_name_exists: True
     # with_dict: "{{ vm_facts.virtual_machines }}"
     # when: item.key == vm_name
    - debug:
        msg: "{{ vm_facts }}"