---

# This is the root playbook for any tasks that run on the domain controllers.
# Please see README.md for more information.

# Execute template on Domain Controller inventory

- name: Determine correct DCs
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - include_vars:
      file: vars/domain-config-vars.yml

  - name: Define DCs for EXPERIANUK
    set_fact:
      domain_controller_1: "{{ dc_experianuk_1 }}"
      domain_controller_2: "{{ dc_experianuk_2 }}"
      domain_controller_3: "{{ dc_experianuk_3 }}"
      domain_controller_4: "{{ dc_experianuk_4 }}"
    when: domain == 'uk.experian.local'

  - name: Define DCs for GDC
    set_fact:
      domain_controller_1: "{{ dc_gdc_1 }}"
      domain_controller_2: "{{ dc_gdc_2 }}"
      domain_controller_3: "{{ dc_gdc_3 }}"
      domain_controller_4: "{{ dc_gdc_4 }}"
    when: domain == 'gdc.local'

  - name: Define DCs for IPANI
    set_fact:
      domain_controller_1: "{{ dc_ipani_1 }}"
      domain_controller_2: "{{ dc_ipani_2 }}"
      domain_controller_3: "{{ dc_ipani_3 }}"
      domain_controller_4: "{{ dc_ipani_4 }}"
    when: domain == 'ipani.uk.experian.com'

- name: Connect to DCs
  hosts: "{{ hostvars['localhost']['domain_controller_1'] }} {{ hostvars['localhost']['domain_controller_2'] }} {{ hostvars['localhost']['domain_controller_3'] }} {{ hostvars['localhost']['domain_controller_4'] }}"
  gather_facts: no
  ignore_unreachable: yes
  tasks:

  - include_vars:
      file: vars/domain-config-vars.yml

  - name: Test connection to DCs
    win_ping:
    register: dc_ping_result

  - name: Run once on a succesfull DC
    block:

    - include_role:
        name: windows/add-domain-groups
      when: os_class == 'Windows Server'

    - include_role:
        name: windows/add-compacc
      when: os_class == 'Windows Server'

    - set_fact:
        dc_success: true
    
    when: dc_ping_result.ping is defined
    run_once: true

  - fail:
      msg: 'Failed to communicate with any DC'
    when:
      - hostvars[ansible_play_hosts[0]]['dc_success'] is undefined
      - hostvars[ansible_play_hosts[1]]['dc_success'] is undefined
      - hostvars[ansible_play_hosts[2]]['dc_success'] is undefined
      - hostvars[ansible_play_hosts[3]]['dc_success'] is undefined
    