---
# tasks file for server-restart
#- name: Task execution for server restart
- name: Task execution from role to ping localhost
  ping:
- name: Display the variable "message" passed from ansible playbook with -e
  shell: echo "Hello {{ message }}"
  ignore_errors: True
  register: result
- debug: 
    var: result
