---
# Created by Michael Barron 20/03/2019
# Modified by Michael Barron 21/03/2019
# Add Windows Server to SolarWinds

- hosts: all
  gather_facts: False
  tasks:

# Execute Add_Server_VisionApp.ps1 to server
  - name: Run Add_Server_Solarwinds.ps1
    #win_command: "C:/tmp/Add_Server_Solarwinds.ps1 -serverName  \"{{ targetServer }}\" -ipAddress \"{{ ansible_ip_addresses[0] }}\""
    win_shell: "C:/ProgramData/Experian/SSC/Add_Server_Solarwinds.ps1 -serverName  \"{{ serverName }}\" -ipAddress \"{{ ipAddress }}\""
    run_once: true
