---
# Created by Michael Barron 27/03/2019
# Modified by Michael Barron 27/03/2019
# Service Acceptance check that runs on the Target Server

- hosts: all
  tasks:

##################################################################################
###### Check if Backup adapter exists and register backup_required variable ######
##################################################################################

  - name: Check Backup Network Adpater exists
    win_shell: |
      Get-NetAdapter -Name "Backup" –ErrorAction SilentlyContinue
    register: backup_check
    ignore_errors: yes
    check_mode: no

  - debug:
      var: backup_check

  - name: Register backup_required if backup NIC exists
    register: backup_required
    when: backup_check.rc != 0

##################################################################################
########## Check RDP and Admin Accounts have been added to the server ############
##################################################################################

  # Work out short domain name from full doamin name and store as fact
  - name: Define short name for EXPERIANUK
    set_fact:
      short_domain: EXPERIANUK
    when: ansible_windows_domain == 'uk.experian.local'

  - name: Define short name for GDC
    set_fact:
      short_domain: GDC
    when: ansible_windows_domain == 'gdc.local'

  - name: Define short name for IPANI
    set_fact:
      short_domain: IPANIUK
    when: ansible_windows_domain == 'ipani.uk.experian.com'

# Work out Admin and RDP Group names from hostname and store as fact
  - name: Define Admin Group Name
    set_fact:
      admin_account: "WS-ADM_{{ ansible_hostname }}"
  
  - name: Define RDP Group Name
    set_fact:
      rdp_account: "WS-STD_{{ ansible_hostname }}"

# Local access groups exist created by Configure Local Group Access role Admin
  - name: Check local Admin Group membership
    win_group_membership:
      name: Administrators
      members:
        - "{{ short_domain }}\\{{ admin_account }}"
      state: present
    register: local_admin_group

# Local access groups exist created by Configure Local Group Access role RDP
  - name: Check local RDP Group membership
    win_group_membership:
      name: Remote Desktop Users
      members:
        - "{{ short_domain }}\\{{ rdp_account }}"
      state: present
    register: local_rdp_group

# Check if the Check local Admin Group membership changed anything
  - name: Check if the Check local Admin Group membership changed anything
    fail:
      msg: "Group Doesnt Exist {{ admin_account }}"
    when: local_admin_group.changed == true

# Check if the Check local Admin Group membership changed anything
  - name: Check if the Check local RDP Group membership changed anything
    fail:
      msg: "Group Doesnt Exist {{ rdp_account }}"
    when: local_rdp_group.changed == true

# Success Debug
  - name: Success Debug
    debug:
      msg: "Both the Admin and RDP groups exist on the server"
    when:
      - local_admin_group.changed == false
      - local_rdp_group.changed == false

##################################################################################
############# Check FireEye is installed when not a Database server ##############
##################################################################################

# Check FireEye is installed if not a Database server block
  - name: Block for executing command only when not Database
    block:

# Gather FireEye Registry version key value
    - name: Gather FireEye version from Registry
      win_reg_stat:
        path: HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{D82800D5-27A8-4FAC-9564-3F700157BA2F}\
        name: DisplayVersion
      register: fireeye_results

# Debug FireEye results var
    - name: Debug FireEye Results var
      debug:
        var: fireeye_results
    
    - name: FireEye Version Check
      debug:
        msg: "Fireeye required Version is {{ fireEye_Version }} installed version is {{ fireeye_results.value }}"
      when:
        - fireeye_results.value == fireEye_Version
        - fireeye_results is defined

    - name: Fail if FireEye is not installed
      fail:
        msg: "FireEye not found or is the incorrect version!"
      when: fireeye_results is undefined or fireeye_results.value != fireEye_Version

# FireEye Block End
    when:
      - server_role != 'Database'

##################################################################################
############# Check that interfaces called Prinary and Backup exist ##############
##################################################################################
# "Check that interfaces called Prinary and Backup exist"
  
  - name: Check Primary Network Adapter exists
    win_shell: |
      Get-NetAdapter -Name "Primary" –ErrorAction SilentlyContinue
    register: primary_nic
    ignore_errors: yes
    check_mode: no

  - debug:
      var: primary_nic

  - name: Fail if no Primary Network Adapter found
    fail:
      msg: "Primary NIC not found!"
    when: primary_nic.rc != 0

# Backup Required Block
  - name: Block for executing command only when backup required
    block:

    - name: Check Backup Network Adpater exists
      win_shell: |
        Get-NetAdapter -Name "Backup" –ErrorAction SilentlyContinue
      register: backup_nic
      ignore_errors: yes
      check_mode: no

    - debug:
        var: backup_nic

    - name: Fail if no Backup Network Adapter found
      fail:
        msg: "Backup NIC not found!"
      when: backup_nic.rc != 0

# Backup Required Block end
    when: 
      - backup_required is defined

##################################################################################
####################### Checks required accounts exist ###########################
##################################################################################

# Check that CCAdmin Account exists and is a member of Administrators
  - name: Check that CCAdmin Account exists and is a member of Administrators
    win_group_membership:
      name: Administrators
      members:
        - "CCAdmin"
      state: present
    register: CCAdmin_user

# Check if the Check local Admin Group membership changed anything
  - name: Check if the Check CCAdmin changed anything
    fail:
      msg: "User Doesnt Exist CCAdmin"
    when: CCAdmin_user.changed == true

# Check that the Arcsight Account is a member of the event log readers group
  - name: Ensure user Arcsight is present EXPERIANUK Domain
    win_group_membership:
      name: Event Log Readers
      members:
        - "{{ short_domain }}\\arcsight"
      state: present
    register: arcsight_user
    when: "'uk.experian.local' in ansible_domain"

  - name: Ensure user ArcSvc is present GDC.LOCAL Domain
    win_group_membership:
      name: Event Log Readers
      members:
        - "{{ short_domain }}\\arcsvc"
      state: present
    register: arcsight_user
    when: "'gdc' in ansible_domain"

  - name: Ensure user Arcsight is present IPANI.UK.EXPERIAN.COM Domain
    win_group_membership:
      name: Event Log Readers
      members:
        - "{{ short_domain }}\\arcsight"
      state: present
    register: arcsight_user
    when: "'ipani' in ansible_domain"

# Check if the Check Arcsight changed anything
  - name: Check if the Check Arcsight changed anything
    fail:
      msg: "User Doesnt Exist {{ short_domain }}\\Arcsight"
    when: arcsight_user.changed == true

# Check that SS000DA exists and is in administrators group.
  - name: Check that SS000DA Account exists and is a member of Administrators
    win_group_membership:
      name: Administrators
      members:
        - "ss000da"
      state: present
    register: ss000da_user

# Check if the Check SS000DA changed anything
  - name: Check if the Check SS000DA changed anything
    fail:
      msg: "User Doesnt Exist SS000DA"
    when: ss000da_user.changed == true

# GDC Block
  - name: Block for executing when GDC
    block:

# Check that sndlgdc exists and is in administrators group.
    - name: Check that sndlgdc Account exists and is a member of Administrators GDC
      win_group_membership:
        name: Administrators
        members:
          - "{{ short_domain }}\\sndlgdc"
        state: present
      register: sndlgdc_user

# Check if the Check sndlgdc changed anything
    - name: Check if the Check sndlgdc changed anything
      fail:
        msg: "User Doesnt Exist {{ short_domain }}\\sndlgdc"
      when: sndlgdc_user.changed == true

# Check that ADMIN EGOC Operations exists and is in administrators group.
    - name: Check that ADMIN EGOC Operations Account exists and is a member of Administrators GDC
      win_group_membership:
        name: Administrators
        members:
          - "{{ short_domain }}\\ADMIN EGOC Operations"
        state: present
      register: EGOC_OP_user

# Check if the Check ADMIN EGOC Operations changed anything
    - name: Check if the Check ADMIN EGOC Operations changed anything
      fail:
        msg: "UserDoesnt Exist {{ short_domain }}\\ADMIN EGOC Operations"
      when: EGOC_OP_user.changed == true

# Check that ADMIN DSG Engineers exists and is in administrators group.
    - name: Check that ADMIN DSG Engineers Account exists and is a member of Administrators GDC
      win_group_membership:
        name: Administrators
        members:
          - "{{ short_domain }}\\ADMIN DSG Engineers"
        state: present
      register: ADMIN_DSG_user

# Check if the Check ADMIN DSG Engineers changed anything
    - name: Check if the Check ADMIN DSG Engineers changed anything
      fail:
        msg: "User Doesnt Exist {{ short_domain }}\\ADMIN DSG Engineers"
      when: ADMIN_DSG_user.changed == true

# GDC Block End
    when:
      - ansible_windows_domain == 'gdc.local'

# IPANIUK Block
  - name: Block for executing when IPANIUK
    block:

# Check that sndipaniuk exists and is in administrators group.
    - name: Check that sndipaniuk Account exists and is a member of Administrators IPANIUK
      win_group_membership:
        name: Administrators
        members:
          - "{{ short_domain }}\\sndipaniuk"
        state: present
      register: sndipaniuk_user

# Check if the Check sndipaniuk changed anything
    - name: Check if the Check sndipaniuk changed anything
      fail:
        msg: "User Doesnt Exist {{ short_domain }}\\sndipaniuk"
      when: sndipaniuk_user.changed == true

# Check that Domain Admins exists and is in administrators group.
    - name: Check that Domain Admins Account exists and is a member of Administrators IPANIUK
      win_group_membership:
        name: Administrators
        members:
          - "{{ short_domain }}\\Domain Admins"
        state: present
      register: domain_admin_user

# Check if the Check Domain Admins changed anything
    - name: Check if the Check Domain Admins changed anything
      fail:
        msg: "User Doesnt Exist {{ short_domain }}\\Domain Admins"
      when: domain_admin_user.changed == true

# Check that ts command centre all users exists and is in administrators group.
    - name: Check that ts command centre all users Account exists and is a member of Administrators IPANIUK
      win_group_membership:
        name: Administrators
        members:
          - "{{ short_domain }}\\ts command centre all users"
        state: present
      register: command_user

# Check if the Check ts command centre all users changed anything
    - name: Check if the Check ts command centre all users changed anything
      fail:
        msg: "User Doesnt Exist {{ short_domain }}\ts command centre all users"
      when: command_user.changed == true

# Check that ts-t-hs-serverops exists and is in administrators group.
    - name: Check that ts-t-hs-serverops Account exists and is a member of Administrators IPANIUK
      win_group_membership:
        name: Administrators
        members:
          - "{{ short_domain }}\\ts-t-hs-serverops"
        state: present
      register: ts_t_user

# Check if the Check ts-t-hs-serverops changed anything
    - name: Check if the Check ts-t-hs-serverops changed anything IPANIUK
      fail:
        msg: "User Doesnt Exist {{ short_domain }}\\ts-t-hs-serverops"
      when: ts_t_user.changed == true

# IPANIUK Block End
    when:
      - ansible_windows_domain == 'ipani.uk.experian.com'

# EXPERIANUK Block
  - name: Block for executing when EXPERIANUK
    block:

# Check that snduk exists and is in administrators group.
    - name: Check that snduk Account exists and is a member of Administrators EXPERIANUK
      win_group_membership:
        name: Administrators
        members:
          - "{{ short_domain }}\\snduk"
        state: present
      register: snduk_user

# Check if the Check snduk changed anything
    - name: Check if the Check snduk changed anything
      fail:
        msg: "User Doesnt Exist {{ short_domain }}\\snduk"
      when: snduk_user.changed == true

# Check that ts command centre all users exists and is in administrators group.
    - name: Check that ts command centre all users Account exists and is a member of Administrators EXPERIANUK
      win_group_membership:
        name: Administrators
        members:
          - "{{ short_domain }}\\ts command centre all users"
        state: present
      register: command_user

# Check if the Check ts command centre all users changed anything
    - name: Check if the Check ts command centre all users changed anything
      fail:
        msg: "User Doesnt Exist {{ short_domain }}\\ts command centre all users"
      when: command_user.changed == true

# Check that ts-t-hs-serverops exists and is in administrators group.
    - name: Check that ts-t-hs-serverops Account exists and is a member of Administrators EXPERIANUK
      win_group_membership:
        name: Administrators
        members:
          - "{{ short_domain }}\\ts-t-hs-serverops"
        state: present
      register: ts_t_user

# Check if the Check ts-t-hs-serverops changed anything
    - name: Check if the Check ts-t-hs-serverops changed anything
      fail:
        msg: "User Doesnt Exist {{ short_domain }}\\ts-t-hs-serverops"
      when: ts_t_user.changed == true

# Check that tdmukuser exists and is in administrators group.
    - name: Check that tdmukuser Account exists and is a member of Administrators EXPERIANUK
      win_group_membership:
        name: Administrators
        members:
          - "{{ short_domain }}\\tdmukuser"
        state: present
      register: tdmukuser_user

# Check if the Check tdmukuser changed anything
    - name: Check if the Check tdmukuser changed anything EXPERIANUK
      fail:
        msg: "User Doesnt Exist {{ short_domain }}\tdmukuser"
      when: tdmukuser_user.changed == true

# EXPERIANUK Block End
    when:
      - ansible_windows_domain == 'uk.experian.local'

# Check that Domain Admins has been removed from local administrators GDC and EXPRIANUK Only

# EXPERIANUK Block
  - name: Block for executing when EXPERIANUK
    block:

# Check that Domain Admins doesnt exists in administrators
    - name: Check that Domain Admins Account doesnt exists in Administrators EXPERIANUK
      win_group_membership:
        name: Administrators
        members:
          - "{{ short_domain }}\\Domain Admins"
        state: absent
      register: Domain_Admins_user

# Check if the Check Domain Admins changed anything
    - name: Check if the Check Domain Admins changed anything EXPERINAUK
      fail:
        msg: "{{ short_domain }}\\Domain Admins has not been removed from the local administrators group"
      when: Domain_Admins_user.changed == true

# EXPERIANUK Block End
    when:
      - ansible_windows_domain == 'uk.experian.local'

# GDC Block
  - name: Block for executing when GDC
    block:

# Check that Domain_Admins doesnt exists in administrators
    - name: Check that Domain Admins Account doesnt exists in Administrators GDC
      win_group_membership:
        name: Administrators
        members:
          - "{{ short_domain }}\\Domain Admins"
        state: absent
      register: Domain_Admins_user

# Check if the Check Domain Admins changed anything
    - name: Check if the Check Domain Admins changed anything GDC
      fail:
        msg: "{{ short_domain }}\\Domain Admins has not been removed from the local administrators group"
      when: Domain_Admins_user.changed == true

# GDC Block End
    when:
      - ansible_windows_domain == 'gdc.local'

#Check that various groups/users have been removed from local administrators in case server was created in the computers container EXPERIANUK Only

# EXPERIANUK Block
  - name: Block for executing when EXPERIANUK
    block:

# Check that ADMIN Workstation Administration doesnt exists in administrators
    - name: Check that ADMIN Workstation Administration Account doesnt exists in Administrators EXPERIANUK
      win_group_membership:
        name: Administrators
        members:
          - "{{ short_domain }}\\ADMIN Workstation Administration"
        state: absent
      register: Admin_ws_user

# Check if the Check ADMIN Workstation Administration changed anything
    - name: Check if the Check ADMIN Workstation Administration changed anything EXPERIANUK
      fail:
        msg: "{{ short_domain }}\\ADMIN Workstation Administration has not been removed from the local administrators group"
      when: Admin_ws_user.changed == true

# Check that CL-T-DskAdmin doesnt exists in administrators
    - name: Check that CL-T-DskAdmin Account doesnt exists in Administrators EXPERIANUK
      win_group_membership:
        name: Administrators
        members:
          - "{{ short_domain }}\\CL-T-DskAdmin"
        state: absent
      register: DskAdmin_user

# Check if the Check CL-T-DskAdmin changed anything
    - name: Check if the Check CL-T-DskAdmin changed anything EXPERIANUK
      fail:
        msg: "{{ short_domain }}\\CL-T-DskAdmin has not been removed from the local administrators group"
      when: DskAdmin_user.changed == true

# Check that Dept_BN_PCSupport doesnt exists in administrators
    - name: Check that Dept_BN_PCSupport Account doesnt exists in Administrators EXPERIANUK
      win_group_membership:
        name: Administrators
        members:
          - "{{ short_domain }}\\Dept_BN_PCSupport"
        state: absent
      register: PCSupport_user

# Check if the Check Dept_BN_PCSupport changed anything
    - name: Check if the Check Dept_BN_PCSupport changed anything EXPERIANUK
      fail:
        msg: "{{ short_domain }}\\Dept_BN_PCSupport has not been removed from the local administrators group"
      when: PCSupport_user.changed == true

# Check that SSMgmtWKUKSvc doesnt exists in administrators
    - name: Check that SSMgmtWKUKSvc Account doesnt exists in Administrators EXPERIANUK
      win_group_membership:
        name: Administrators
        members:
          - "{{ short_domain }}\\SSMgmtWKUKSvc"
        state: absent
      register: SSMgmtWKUKSvc_user

# Check if the Check SSMgmtWKUKSvc changed anything
    - name: Check if the Check SSMgmtWKUKSvc changed anything EXPERIANUK
      fail:
        msg: "{{ short_domain }}\\SSMgmtWKUKSvc has not been removed from the local administrators group"
      when: SSMgmtWKUKSvc_user.changed == true

# EXPERIANUK Block End
    when:
      - ansible_windows_domain == 'uk.experian.local'

##################################################################################
########################## Checks required Services ##############################
##################################################################################

#Check that Telnet Client is installed