###########################################################################
#   SSC Automation - Windows Build - GSA User Group Creation - dsadd
#   Confluence:
#   Create GSA User Groups in Domain
#   Author: Kristiyan Nikolov
#   Creation Date: 28/03/19
###########################################################################
#Domain Controllers
#experianukdclist=( corp-not-ukdc09 corp-not-ukdc02 corp-not-ukdc10 )
#ipanidclist=( corp-not-ipdc01 corp-not-ipdc02 corp-not-ipdc03 )
#gdcdclist=( corp-not-gdc01 corp-not-gdc02 )


---
- name: AD Group Creation Domain Controller Selection 1
  hosts: "{{ dc1 }}"
  gather_facts: no
  tasks:

#  - name: Test connection to DC1
#    win_ping:
#    ignore_unreachable: yes
#    register: result1

#  - debug:
#      var: result1

  - name: Create Administrator Group
#    win_shell: dsadd group cn={{ adm_group }},{{ ou }} -desc "Windows Server Local Administrator access group"
#    when: result1 is success
    win_shell: hostname 

#  - name: Create Remote Desktop istrator Group
 #   win_shell: dsadd group cn={{ std_group }},{{ ou }} -desc "Windows Server Remote Desktop access group"
 #   when: result1 is success

  #- fail:
   #   msg: "No live Domain Contoller could be found."
    #when: hostvars[dc1]['result1'] is failed and hostvars[dc2]['result2'] is failed