---
# Created by Michael Barron 25/03/2019
# Modified by Michael Barron 25/03/2019
# Deploy And Run Windows Backup Script

- hosts: all
  gather_facts: False
  tasks:

# Ensure Windows Backup feature is installed
  - name: Ensure Windows Backup Feature is installed
    win_feature:
      name: Windows-Server-Backup
      state: present
      restart: no

# Create Backup on Target server
  - name: create backup of c:\ to y:\
    win_command: wbadmin start backup -backupTarget:Y:\ -include:C:\ -allCritical -systemState -vssCopy -quiet
