---
- name: Pre-stage comp acc testing
  hosts: CORP-NOT-IPDC02
  gather_facts: no
  tasks:

  - name: Create computer account in 2016 OU
    win_domain_computer:
      name: "{{ adname }}"
      sam_account_name: "{{ sam }}"
      dns_hostname: "{{ dns }}"
      ou: "{{ ou }}"
      description: Windows 2016 server created by ETIG Automation
      enabled: yes
      state: present