---
# This script will validate the backup network vLan in vCenter
- name: Validating backup vLan in vCenter
  set_fact:
    backup_network_exists: True
  with_items: "{{ vNetwork.json.value }}"
  when: item.name == Backup_VLAN
- fail:
    msg: "Backup Network[{{ Backup_VLAN }}] not present in the vCenter Server[{{ VC_Server_Name }}]"
  when: not backup_network_exists
- debug:
    msg:  "Backup Network[{{ Backup_VLAN }}] present in the vCenter Server[{{ VC_Server_Name }}]"
