---

  - name: Login to vCenter API
    uri:
      url: "https://{{ vcenter_hostname }}/rest/com/vmware/cis/session"
      force_basic_auth: yes
      validate_certs: False
      method: POST
      user: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
    register: login
