---

  - name: Create vCenter folder [{{ vcenter_folder }}]
    vcenter_folder:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vcenter_datacenter }}"
      folder_name: "{{ vcenter_folder }}"
      folder_type: vm
      validate_certs: False
      state: present
    register: vm_folder_creation_result
    delegate_to: localhost

