---

  - name: Set DNS config for EXPERIANUK  
    set_fact:
      short_domain: EXPERIANUK
      primary_dns: 10.215.252.10
      secondary_dns: 10.173.251.106
      domain_admin_user: "{{ domain_admin_uk_experian_local }}"
      domain_admin_pwd: "{{ domain_password_uk_experian_local }}"
    when: domain is defined and domain == 'uk.experian.local'

  - name: Set DNS config for GDC
    set_fact:
      short_domain: GDC
      primary_dns: 10.188.21.1
      secondary_dns: 10.188.21.2
      domain_admin_user: "{{ domain_admin_gdc_local }}"
      domain_admin_pwd: "{{ domain_password_gdc_local }}"
    when: domain is defined and domain == 'gdc.local'

  - name: Set DNS config for IPANIUK
    set_fact:
      short_domain: IPANIUK
      primary_dns: 194.60.173.145
      secondary_dns: 194.60.173.146
      domain_admin_user: "{{ domain_admin_ipani_experian_local }}"
      domain_admin_pwd: "{{ domain_password_ipani_experian_local }}"
    when: domain is defined and domain == 'ipani.uk.experian.com'
