---
- name: Gather all registered virtual machines
  hosts: localhost
  connection: local
  vars:
    vcenter_hostname: ukfhpcbvcs02.uk.experian.local
    vcenter_username: 'EXPERIANUK\BladeLogicVMware'
    vcenter_password: 4hQzYa7F5hNFmLvj
    vm_name: "ACITest1"
  tasks:
    - name: "Testing module vmware_vm_facts"
      vmware_vm_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
      delegate_to: localhost
      register: vm_facts
    - set_fact:
        vm_name_exists: True
        
      with_dict: "{{ vm_facts.virtual_machines }}"
      when: item.key == vm_name
       
