---
- name: Vcenter access check
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    vcenter_hostname: ukfhpcbvcs02.uk.experian.local
    vcenter_username: 'EXPERIANUK\BladeLogicVMware'
    vcenter_password: 4hQzYa7F5hNFmLvj
    datacenter_name: "Fairham"
    datastore_cluster_name: "FH_40-Core_Win-01_T1-NR"

  tasks:
    - name: Create datastore cluster
      vmware_datastore_cluster:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter_name: '{{ datacenter_name }}'
        datastore_cluster_name: '{{ datastore_cluster_name }}'
        validate_certs: False
        state: present
      delegate_to: localhost

