---
# tasks file for Add-DNS

- name: Set uk.experian.local DC hosts
  set_fact:
    hostNode1: "{{ experianuk_hostnode_01 }}"
    hostNode2: "{{ experianuk_hostnode_02 }}"
  when: ansible_windows_domain is defined and ansible_windows_domain == 'uk.experian.local'

- name: copy file {{ file_name }} to windows tmp directory
  win_copy:
   #src: "{{ file_name }}"
   src: "test.ps1"
   dest: "{{ windows_temp_path }}\\{{ file_name }}"
   when: hostNode1 is defined and hostNode2 is defined
   
- name:  Run remote powershell script
  win_command: powershell.exe -ExecutionPolicy ByPass -File {{ windows_temp_path }}\\{{ file_name }}
  ignore_errors: True
  register: _out
  when: hostNode1 is defined and hostNode2 is defined

- debug:
   msg: "The host are : {{ _out.stdout_lines,hostNode1,hostNode2 }}"
  when: hostNode1 is defined and hostNode2 is defined
