---
# tasks file for prestage-computer-account
- name: Set uk.experian.staging DC hosts
  set_fact:
    hostNode1: "{{ experian_stage_hostnode_01 }}"
    hostNode2: "{{ experian_stage_hostnode_02 }}"
  when: domain is defined and domain == 'uk.experian.staging'
- name: Set uk.experian.local DC hosts  
  set_fact:
    hostNode1: "{{ experianuk_hostnode_01 }}"
    hostNode2: "{{ experianuk_hostnode_02 }}"
  when: domain is defined and domain == 'uk.experian.local'
- name: Set gdc.local DC hosts   
  set_fact:
    hostNode1: "{{ gdc_hostnode_01 }}"
    hostNode2: "{{ gdc_hostnode_02 }}"
  when: domain is defined and domain == 'gdc.local'
- name: Set ipani.uk.experian.local DC hosts   
  set_fact:
    hostNode1: "{{ ipani_hostnode_01 }}"
    hostNode2: "{{ ipani_hostnode_02 }}"
  when: domain is defined and domain == 'ipani.uk.experian.local'
- name: copy file {{ file_name }} to windows tmp directory
  win_copy:
   #src: "{{ file_name }}"
   src: "test.ps1"   
   dest: "{{ windows_temp_path }}{{ file_name }}"
  when: hostNode1 is defined and hostNode2 is defined
- name:  Run remote powershell script
  win_shell: "{{ windows_temp_path }}{{ file_name }} -Computer {{ ansible_hostname }} -Domain {{ domain }} -OS \"{{ os_name }}\""
  args: 
    executable: powershell
  #ignore_errors: True
  register: _out
  when: hostNode1 is defined and hostNode2 is defined
  
- debug:
   msg: "{{ _out.stdout_lines,ansible_hostname,domain,os_name,hostNode1,hostNode2 }}" 
