---
# This script have a credentail details for Rest API scripts
- name: Login into vCenter
  uri:
    url: "https://{{ VC_Server_Name }}/rest/com/vmware/cis/session"
    force_basic_auth: yes
    validate_certs: False
    method: POST
    user: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
  register: login
