---
- name: If the backup required is no
  set_fact:
   Assigned_Backup_IP_Address: "192.168.0.100"
   Assigned_Backup_Subnet_Mask: "255.255.255.0"
   Assigned_Backup_VLAN: "SBN|backup|clients"
  when: Backup_Required|lower == "no"
- name: If the backup required is yes
  set_fact:
   Assigned_Backup_IP_Address: "{{ Backup_IP_Address }}"
   Assigned_Backup_Subnet_Mask: "{{ Backup_Subnet_Mask }}"
   Assigned_Backup_VLAN: "{{ Backup_VLAN }}"
  when: Backup_Required|lower == "yes"
- debug:
    msg: "Backup LAN values set are Backup_IP_Address[{{ Assigned_Backup_IP_Address }}],Backup_Subnet_Mask[{{ Assigned_Backup_Subnet_Mask }}],Backup_VLAN[{{ Assigned_Backup_VLAN }}]"