---
# Set customization specification w.r.t. the vm domain it belongs to
# $Windows_Domain will come as an input from SNOW
- name: Set uk.experian.local DC hosts  
  set_fact:
#    Customization_Spec_Name: IAAS Windows Server 2008/2012/2012R2/2016 In uk.experian.local Domain
    Primary_DNS: 10.215.252.10
    Secondary_DNS: 10.173.251.106
    Primary_WINS: 10.215.252.12
    Secondary_WINS: 10.173.243.146  
    domain_admin_user: "{{ domain_admin_uk_experian_local }}"
    domain_admin_pwd: "{{ domain_password_uk_experian_local }}"
  when: Windows_Domain is defined and Windows_Domain == 'uk.experian.local'

- name: Set gdc.local DC hosts
  set_fact:
#    Customization_Spec_Name: IAAS Windows Server 2008/2012/2012R2/2016 In GDC.Local Domain
    Primary_DNS: 10.188.21.1
    Secondary_DNS: 10.188.21.2
    Primary_WINS: 
    Secondary_WINS:
    domain_admin_user: "{{ domain_admin_gdc_local }}"
    domain_admin_pwd: "{{ domain_password_gdc_local }}"
  when: Windows_Domain is defined and Windows_Domain == 'gdc.local'

- name: Set ipani.uk.experian.com DC hosts
  set_fact:
#    Customization_Spec_Name: IAAS Windows Server 2008/2012/2012R2/2016 In ipani.uk.experian.com Domain
    Primary_DNS: 194.60.173.145
    Secondary_DNS: 194.60.173.146
    Primary_WINS:
    Secondary_WINS:
    domain_admin_user: "{{ domain_admin_ipani_experian_local }}"
    domain_admin_pwd: "{{ domain_password_ipani_experian_local }}"
  when: Windows_Domain is defined and Windows_Domain == 'ipani.uk.experian.com'

- name: Set Workgroup DC hosts   
  set_fact:
#   Customization_Spec_Name: IAAS Windows Server 2008/2012/2012R2/2016 In WORKGROUP
    Primary_DNS: 10.215.252.10
    Secondary_DNS: 10.173.251.106
    Primary_WINS: 
    Secondary_WINS:
  when: Windows_Domain is defined and Windows_Domain|lower == 'workgroup'

- name: Set uk.experian.staging DC hosts   
  set_fact:
#    Customization_Spec_Name: IAAS Windows Server 2008/2012/2012R2/2016 In uk.experian.staging Domain
    Primary_DNS: 10.215.243.7
    Secondary_DNS: 
    Primary_WINS: 
    Secondary_WINS:
    domain_admin_user: "{{ domain_admin_uk_experian_staging }}"
    domain_admin_pwd: "{{ domain_password_uk_experian_staging }}"
  when: Windows_Domain is defined and Windows_Domain == 'uk.experian.staging'
- debug:
    msg: "Primary_DNS[{{ Primary_DNS }}],Secondary_DNS[{{ Secondary_DNS }}],Primary_WINS[{{ Primary_WINS }}],Secondary_WINS[{{ Secondary_WINS }}],domain_admin_user[{{ domain_admin_user }}]"
