---
# This script will validate the backup network vLan in vCenter
- name: Get Network Backup Vlan from vCenter
  uri:
    url: https://{{ VC_Server_Name }}/rest/vcenter/network?filter.names.1={{ Backup_VLAN }}
    force_basic_auth: yes
    validate_certs: False
    headers:
      Cookie: "{{ login.set_cookie }}"
  register: vBackupNetwork

- name: Validating backup vLan in vCenter
  set_fact:
    backup_network_exists: True
  with_items: "{{ vBackupNetwork.json.value }}"
  when: item.name == Backup_VLAN
- fail:
    msg: "Backup Network[{{ Backup_VLAN }}] not present in the vCenter Server[{{ VC_Server_Name }}]"
  when: ((Backup_Required|lower == "yes") and (not backup_network_exists))
- debug:
    msg:  "Backup Network[{{ Backup_VLAN }}] present in the vCenter Server[{{ VC_Server_Name }}]"
  when: Backup_Required|lower == "yes"
