---
# Created by Michael Barron 13/03/2019
# Modified by Michael Barron 13/03/2019
# Update Disallowed and Auth Certs

- hosts: all
  tasks:

# Copy Auth Certs files to Server.
    - name: Copy Auth Certs files to Server
      win_copy:
        src: "{{ sourcePath }}"
        dest: C:\tmp\certs

# Run Add Auth Certs Batch file
    - name: Run Add Auth Certs Batch file
      win_command: C:\tmp\certs\deploycerts.cmd

# Remove Auth Certs files from Server.
    - name: Remove Auth Certs files to Server
      win_file:
       path: C:\tmp\certs
       state: absent
