---
- name: apache2
  hosts: host01
  become: True
  tasks:
    - name: Install apache2
      apt: name=apache2 state=present update_cache=true
    - name: Check apache2 Started
      service: name=apache2 state=started


- name: sqlite3
  hosts: host01
  become: True
  tasks:
    - name: Install sqlite3
      apt: name=sqlite3 state=present update_cache=true


- name: git
  hosts: host01
  become: True
  tasks:
    - name: Install git
      apt: name=git state=present update_cache=true
...
