---
# tasks file for nvsbind

- name: Copy nvsbind exe file to system32
  win_copy:
   src: "{{ item }}"
   dest: 'C:\Windows\System32\{{ item }}'
  with_items:
  - "nvspbind.exe"
  - "nvspbind-x86.exe"
