---
# Updated by Michael Barron 28/01/2019
# Java JDK install
# Command Line options https://docs.oracle.com/javase/7/docs/webnotes/install/windows/jdk-installation-windows.html#notation
- hosts: all
  tasks:
    - name: copying Java JDK installation media to server
      win_copy:
        src: "{{ sourcePath }}{{ installer }}"
        dest: C:\temp\

    - name: installing JavaJDK
      win_shell: C:\temp\{{ installer }} /s

    - name: Update %PATH% Variable
      win_path:
        elements:
        - 'C:\Program Files\Java\{{ version }}\bin'
        state: present

    - name: removing Java JDK installation media
      win_file:
        path: C:\temp\{{ installer }}
        state: absent
