###########################################################################
#   ETIG Automation - Windows Build - Install Qualys Agent
#   Confluence:
#   Install Qualys Agent
#   Author: Barry Field
#   Creation Date: 21/02/19
#   Last Update Date:22/02/19
###########################################################################


---
- name: Deploy Qualys
  hosts: all
  gather_facts: False
  tasks:

  - name: Copy qualysCloudAgent
    win_copy:
      src: "{{ qualys_source }}"
      dest: C:\tmp\
      state: present

  - name: Install QualysCloudAgent
    win_package:
      path: C:\tmp\{{ installer }}
      creates_path: C:\Program Files\Qualys\QualysAgent\{{ installer }}
      creates_ver: "{{ ver }}"
      arguments: CustomerId=9c0e25dd-f7a3-5af6-e040-10ac13043f6a ActivationId=c3f07e9c-9403-473f-9137-67e594e95333
      state: present
