###########################################################################
# Post-Build - Windows - Add .NET 3.5 to 2012/2016
# Author: Tom Meer
# Creation Date: 04/01/19
# Last Update Date: 23/01/19
###########################################################################

---

- hosts: all
  tasks:

  - name: Define SXS Source for 2016
    set_fact:
      sxs_source: "/resources/BladeLogic/Storage/file_deploy/Windows/Windows 2016 SXS/sources/sxs"
    when: "'2016' in ansible_os_name"

  - name: Define SXS Source for 2012
    set_fact:
      sxs_source: "/resources/BladeLogic/Storage/file_deploy/Windows/Windows 2012 R2 SXS/sxs"
    when: "'2012 R2' in ansible_os_name"

  - name: Copy SXS Directory
    win_copy:
      src: "{{ sxs_source }}"
      dest: C:\Temp

  - name: Add .NET 3.5 Feature
    win_feature:
      name: NET-Framework-Core
      source: C:\Temp\sxs
      state: present

...