---
# created by Michael Barron 25/03/2019
# Modified by Michael Barron 25/03/2019
# Install Tanium

- hosts: all
  gather_facts: False
  tasks:

# Copy Tanium binaries to Target server
  - name: Copy Tanium to Target Server
    win_copy:
      src: "{{ sourcePath }}"
      dest: C:\tmp\Tanium\

# Install Tanium on Target server
  - name: Install Tanium on Target server
    win_package:
      path: C:\tmp\Tanium\InstallTanium.msi
      arguments: /qn /norestart SERVERADDRESS="{{ taniumip1 }},{{ taniumip2 }}"

# Remove Tanium folder
  - name: Remove Tanium folder from Target server
    win_file:
      path: C:\tmp\Tanium
      state: absent
