###########################################################################
#   ETIG Automation - Windows Build - Install Encase
#   Confluence:
#   Install Encase
#   Author: Barry Field
#   Creation Date: 18/03/19
#   Last Update Date:21/03/19
###########################################################################

---
- name: Install Encase
  hosts: all
  gather_facts: no
  tasks:

  - name: Copy installation media to server
    win_copy:
      src: "{{ src_encase_path }}{{ src_encase_installer }}"
      dest: c:\temp\

  - name: Installing Encase
    win_package:
      path: C:\temp\{{ src_encase_installer }}
      arguments: ALLUSERS=1 REBOOT=ReallySuppress
      creates_service: enstart64
      state: present
    register: encase_result

  - name: Reboot server
    win_reboot:
    when: encase_result.reboot_required

  - name: Remove installation media
    win_file:
      path: C:\temp\{{ src_encase_installer }}
      state: absent

