###########################################################################
#   SSC Automation - Windows Build - SQL Pre-Reqs
#   Confluence:
#   Move SQL Install Files
#   Author: Barry Field
#   Creation Date: 28/01/19
#   Last Update Date: 28/01/19
###########################################################################

---
- name: SQL TESTING
  hosts: all
  gather_facts: yes
  become_method: runas
  tasks:

#Begin Tasks

  - name: Copy SXS Directory
    win_copy:
      src: "{{ sxs_source }}"
      dest: C:\tmp
      state: present

  - name: install AD PS Module
    win_feature:
      name: RSAT-AD-Powershell
      source: C:\tmp\sxs
      state: present

  - name: copy ps1 to script host
    win_copy:
      src: SQLServiceAccCreation.ps1
      dest: c:\tmp\

#Define INI File {{ install_template }}
  - name: Define INI file 2016Ent
    set_fact:
        install_template: "C:\\tmp\\SQL\\SQL_Install\\SQL_2016_Ent_x64_inc_SP2\\SQL2016Standalone.ini"
    when: sql_ver == 'SQL2016Ent'

  - name: Define INI file 2016Std
    set_fact:
        install_template: "C:\\tmp\\SQL\\SQL_Install\\SQL_2016_Std_x64_inc_SP2\\SQL2016Standalone.ini"
    when: sql_ver == 'SQL2016Std'

  - name: Define INI file 2017Ent
    set_fact:
        install_template: "C:\\tmp\\SQL\\SQL_Install\\SQL_2017_Ent_x64_RTM\\SQL2017Standalone.ini"
    when: sql_ver == 'SQL2017Ent'

  - name: Define INI file 2017Std
    set_fact:
        install_template: "C:\\tmp\\SQL\\SQL_Install\\SQL_2017_Std_x64_RTM\\SQL2017Standalone.ini"
    when: sql_ver == 'SQL2017Std'

# ## Disable UAC
#   - name: turn UAC off
#     win_regedit:
#       path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\system
#       name: EnableLUA
#       data: 0
#       type: dword
#       state: present
#     register: uac_result

#   - name: reboot after disabling UAC
#     win_reboot:
#     when: uac_result is changed

## Run Service Account Powershell
  - name: Run SQLServiceAccCreation.ps1
    win_shell: "{{ powershellPath1 }} -installTemplate \"{{ install_template }}\" -businessunit \"{{ business_unit }}\" -supportgroup \"{{ support_group }}\""
    #win_command: "powershell.exe -executionpolicy ByPass -File \"{{ powershellPath }}\" -cmdFile \"{{ cmd_File }}\" -workingDir \"{{ working_Dir }}\" -installTemplate \"{{ install_template }}\" -businessunit \"{{ business_unit }}\" -supportgroup \"{{ support_group }}\""
    become: yes
    become_user: SYSTEM
    #vars:
    #  ansible_become_pass: D4nnyR0s3!
    #become_flags: logon_type=interactive
