###########################################################################
# Post-Build - Windows - Add Storage to VMware
# Author: Tom Meer
# Creation Date: 25/01/19
# Last Update Date: 28/01/19
###########################################################################

---

- name: Using "{{ script_host_1 }}"
  hosts: "{{ script_host_1 }}"
  gather_facts: no
  tasks:

  - name: Test connection to "{{ script_host_1 }}"
    win_ping:
    ignore_unreachable: yes
    register: result1

  - name: Execute PowerShell
    win_shell: "{{ powershell_path }} -serverName {{ server_name }} -driveLetter {{ drive_letter }} -driveID 0 -size {{ drive_size }} -sizeUnit GB -task new"
    when: result1 is success

- name: Using "{{ script_host_2 }}"
  hosts: "{{ script_host_2 }}"
  gather_facts: no
  tasks:

  - name: Test connection to "{{ script_host_2 }}"
    win_ping:
    register: result2
    when: hostvars[script_host_1]['result1'] is failed

  - name: Execute PowerShell
    win_shell: "{{ powershell_path }} -serverName {{ server_name }} -driveLetter {{ drive_letter }} -driveID 0 -size {{ drive_size }} -sizeUnit GB -task new"
    when: hostvars[script_host_1]['result1'] is failed

  - fail:
      msg: "No live script host could be found."
    when: hostvars[script_host_1]['result1'] is failed and hostvars[script_host_2]['result2'] is failed
...