###########################################################################
#   SSC Automation - Windows Build - GSA AD Groups to Local Server
#   Confluence:
#   Adds GSA AD Groups to Local Server
#   Author: Barry Field
#   Creation Date: 11/01/19
#   Last Update Date: 11/01/19
###########################################################################

## params from SNow 
# ADM-GroupName
# STD-GroupName


---
- name: Add GSA AD Groups to Local Server
  hosts: all
  gather_facts: no
  tasks:

#win_ping to select DC

#delegate to dc

  - name: Add GSA Admin Group to Local Admin
    win_group_membership:
     name: Administrators
     members:
        - ipani.uk.experian.com\{{adm-groupname}}
     state: present

  - name: Add GSA Admin Group to Remote Desktop Users
    win_group_membership:
     name: 'Remote Desktop Users'
     members:
        - ipani.uk.experian.com\{{std-groupname}}
     state: present