##Group add to Local Testing
---
- name: Add GSA AD Groups to Local Server
  hosts: UKFHPAPCHO01
  gather_facts: no
  tasks:

  - name: Add GSA Admin Group to Remote Desktop Users
    win_group_membership:
     name: Remote Desktop Users
     members:
        - ExperianUK\TS-T-HS-ServerOps
     state: present