---
# Created by Michael Barron 26/03/2019
# Modified by Michael Barron 26/03/2019
# Service Acceptance

- hosts: all
  gather_facts: false
  tasks:

# Check DNS Record exists Forward lookup
#  - name: Check DNS record exists Forward lookup
#    win_command: nslookup {{ serverName }}
#    register: nslookup_out_cmd
#    run_once: true

# Check DNS Record exists Forward lookup
  - name: Check DNS record exists Forward lookup
    win_shell: nslookup {{ serverName }}
    args:
      executable: cmd
    register: nslookup_out_shell
    run_once: true

  - debug:
      var: nslookup_out_shell
    run_once: true

#  - debug:
#      var: nslookup_out_cmd

# Fail if DNS Check fails 
  - name: fail if DNS Check fails 
    fail:
      msg: "DNS Lookup failed!"
    when: "'Non-existent domain' in nslookup_out_shell.stderr"
    run_once: true
