---
# Created by Michael Barron 26/03/2019
# Modified by Michael Barron 26/03/2019
# Service Acceptance checks that run on the script host servers to check a target server

- hosts: all
  gather_facts: false
  tasks:

# Check DNS Record exists Forward lookup
  - name: Check DNS record exists Forward lookup
    win_shell: nslookup {{ serverName }}
    args:
      executable: cmd
    register: nslookup_out_shell
    run_once: true

# Debug nslookup_out_shell
  - debug:
      var: nslookup_out_shell
    run_once: true

# Fail if DNS Check fails 
  - name: Check if DNS Check failed
    set_fact: errors="[ 'DNS' ]"
    when: "'Non-existent domain' in nslookup_out_shell.stderr"
    run_once: true

# Error if errors is not empty
  - name: Fail if any errors
    fail:
      msg: "DNS Lookup failed!"
    when: errors is defined
    run_once: true

# Success if no error
  - name: Success if no errors
    debug:
      msg: "DNS Lookup Success!"
    when: errors is undefined
    run_once: true
