---
- name: unquoted path testing
  hosts: all
  gather_facts: no
  tasks:

  - name: Copy Powershell script to server
    win_copy:
      src: Windows_Path_Enumerate.ps1
      dest: c:\temp\

  - name: Run unquoted path fix
    win_shell: c:\temp\Windows_Path_Enumerate.ps1

  - name: Remove Powershell script from server
    win_file:
      path: c:\temp\Windows_Path_Enumerate.ps1
      state: absent