---
- hosts: all
  tasks:
    - name: Adding {{serverName}} to build inventory
      tower_host:
        name: "{{serverName}}"
        inventory: "Server Builds"
        state: present

    - name: Add host to group {{inventoryGroup}}
      shell: tower-cli host associate --host {{serverName}} --group {{inventoryGroup}}
