---
# This script will validate if the datastore cluster name
# passed as VC_Data_Center_Name from SNOW exists within the
# cluster passed as VC_Cluster_Name from SNOW
- name: "Connection to the vSphere server to collect datastore facts for the cluster[{{ VC_Cluster_Name }}]"
  vmware_datastore_facts:
    hostname: '{{ VC_Server_Name }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ VC_Data_Center_Name }}'
    cluster: '{{ VC_Cluster_Name }}'
    validate_certs: False
  delegate_to: localhost
  register: vc_cluster_facts
- name: "Collect the datastores for the cluster[{{ VC_Cluster_Name }}] and validate that the DataStore Cluster Name[{{ DataStore_Cluster_Name }} name exists"
  set_fact:
    valid_cluster_name: True
  with_items: "{{ vc_cluster_facts['datastores'] }}"
  when: item.datastore_cluster == DataStore_Cluster_Name
- fail:
    msg: "DataStore_Cluster_Name[{{ DataStore_Cluster_Name }}] not present in cluster[{{ VC_Cluster_Name }}]"
  when: not valid_cluster_name
- debug:
    msg: "DataStore_Cluster_Name[{{ DataStore_Cluster_Name }}] present in cluster[{{ VC_Cluster_Name }}]"
    
