---

  - name: Deploy PowerShell file if changed
    win_copy:
      src: Add-VisionAppServer.ps1
      dest: C:\ProgramData\Experian\SSC\

  - name: Run Add_Server_VisionApp.ps1 via psexec
    win_psexec:
      command: "powershell.exe -File C:\\ProgramData\\Experian\\SSC\\Add-VisionAppServer.ps1 -serverName  \"{{ server_name }}\" -Country \"{{ region }}\" -bu \"{{ business_unit }}\" -Service \"{{ sub_business_unit }}\" -domain \"{{ domain }}\" -Function \"{{ server_role }}\""
      executable: C:\ProgramData\Experian\SSC\psexec.exe
      interactive: yes
      chdir: C:\ProgramData\Experian\SSC\
      elevated: yes
      limited: no
      nobanner: yes
      username: "EXPERIANUK\\{{ SIMPLE_USERNAME }}"
      password: "{{ SIMPLE_PASSWORD }}"
    ignore_errors: yes

