---
- name: SQL Pre-Requisites
  hosts: all
  gather_facts: yes
  tasks:

  - name: Copy Source Files Directory
    win_copy:
      src: "{{ sourcePath }}" #determined by SNow based on SQL version selected. Files needed - Install source folder, ini, cmd file, password file, PS scripts
      dest: "{{ destPath }}"
      state: present

