---
# Created by Scott W
- hosts: all
  tasks:
    - name: copy installation media to server
      win_copy:
        src: "{{ sourcePath }}"
        dest: c:\temp\

    - name: installing V File Viewer
      win_shell: C:\temp\{{appFolder}}\{{installer}} /auto /all
       
    - name: removing installation media
      win_file:
       path: C:\temp\{{appFolder}}
       state: absent