###########################################################################
#   ETIG Automation - Windows Build - Install Splunk Forwarder
#   Confluence:
#   Install Splunk Forwarder
#   Author: Kristiyan Nikolov
#   Creation Date: 26/02/19
#   Last Update Date:26/02/19
###########################################################################
- hosts: all
  tasks:
    - name: copy installation media to server
      win_copy:
        src: "{{ sourcePath }}{{ installer }}"
        dest: c:\temp\

    - name: installing Splunk
      win_package:
       path: C:\temp\{{ installer }}
       product_id: '{C05A896E-05F4-49B6-A191-FC29B1362B81}'
       arguments: ALLUSERS=1 REBOOT=ReallySuppress DEPLOYMENT_SERVER="ukfhpcbssu01:8089" WINEVENTLOG_SYS_ENABLE=0 AGREETOLICENSE=Yes /quiet
       state: present

    - name: remove installation media
      win_file:
       path: C:\temp\{{ installer }}
       state: absent

