###########################################################################
#   ETIG Automation - Windows Build - FireEye Endpoint Agent 
#   Confluence:
#   Install FireEye Endpoint Agent
#   Author: Kristiyan Nikolov
#   Creation Date: 06/03/19
#   Last Update Date:06/03/19
###########################################################################
- hosts: all
  tasks:
    - name: copy installation media to server
      win_copy:
        src: "{{ sourcePath }}{{ installer }}"
        dest: c:\temp\

    - name: copy config file to server
      win_copy:
        src: "{{ sourcePath }}{{ config }}"
        dest: c:\temp\

    - name: installing FireEye 25.12.0
      win_package:
       path: C:\temp\{{ installer }}
       product_id: '{D82800D5-27A8-4FAC-9564-3F700157BA2F}'
       arguments: /quiet /l*v C:\Windows\Temp\FireEyeAgent-Install.log /norestart
       state: present

    - name: remove installation media
      win_file:
       path: C:\temp\{{ installer }}
       state: absent

    - name: remove config file
      win_file:
       path: C:\temp\{{ config }}
       state: absent      

