---
# Created by Scott W
- hosts: all
  tasks:
    - name: copy installation media to server
      win_copy:
        src: "{{ sourcePath }}{{ installer }}"
        dest: c:\temp\

    - name: installing Beyond Compare
      win_package:
       path: C:\temp\{{ installer }}
       state: present

    - name: remove installation media
      win_file:
       path: C:\temp\{{ installer }}
       state: absent
