---
# Created by Scott W
- hosts: all
  tasks:
    - name: copy installation media to server
      win_copy:
        src: "{{ sourcePath }}{{ installer }}"
        dest: c:\temp\

    - name: installing Notepad++
      win_shell: C:\temp\{{ installer }} /S
       
    - name: removing installation media
      win_file:
       path: C:\temp\{{ installer }}
       state: absent