###########################################################################
#   SSC Automation - Windows Build - SQL Pre-Reqs
#   Confluence:
#   Move SQL Install Files
#   Author: Barry Field
#   Creation Date: 28/01/19
#   Last Update Date: 28/01/19
###########################################################################

---
- name: SQL Pre-Requisites
  hosts: all
  gather_facts: no
  tasks:

  - name: Copy Source Files Directory
    win_copy:
      src: "{{ sourcePath }}" #determined by SNow based on SQL version selected. Files needed - Install source folder, ini, cmd file, password file, PS scripts
      dest: C:\tmp
      force: no
      state: present

  - name: Copy SXS Directory
    win_copy:
      src: "{{ sxs_source }}"
      dest: C:\tmp
      force: no
      state: present

  - name: install AD PS Module
    win_feature:
      name: RSAT-AD-Powershell
      source: C:\tmp\sxs
      state: present

  - name: copy ps1 to script host
    win_copy:
      src: SQL_Install.ps1
      dest: c:\tmp\

  - name: Unzip SQL Files
    win_unzip:
      src: c:\tmp\SQL2016\SQL_2016_Ent_x64_inc_SP2.zip
      dest: c:\tmp\SQL2016
      creates: c:\tmp\SQL2016\SQL_2016_Ent_x64_inc_SP2

  - name: Install SQL
    win_shell: "{{ powershellPath }} -cmdFile \"{{ cmd_File }}\" -workingDir \"{{ working_Dir }}\" -installTemplate \"{{ install_Template }}\" -sqladminKey \"{{ sqladmin_Key }}\" -sqladminPw \"{{ sqladmin_Pw }}\" -keyFile \"{{ key_File }}\" -txtFile \"{{ txt_File }}\" -sqlCollation \"{{ sql_Collation }}\""
    result: result1

  - name: Remove Source Files
    win_copy:
      src: "{{ sourcePath }}"
      state: absent
      when: result1 is success